### ISSUE TITLE
Don't decode QR_CODE

### ISSUE THREAD

**Issue by kkkaktusss** [micjahn/ZXing.Net#556]
Hi, i have a bit question. When I try to decode image, barcodereader can't find a QR_CODE format, but in "https://zxing.org" this type is recoginzed(attach a proof in picture). 
My code return EAN_8, UPC_E,  but not a QR_CODE.
`                var reader = new BarcodeReader() { AutoRotate = true};
                reader.Options.TryHarder = true;
                reader.Options.PossibleFormats = new BarcodeFormat[] { BarcodeFormat.QR_CODE, BarcodeFormat.EAN_8, BarcodeFormat.UPC_E };
                var result2 = reader.DecodeMultiple(imageMat);`
![2024-03-19_14-57-53](https://github.com/zxing/zxing/assets/66029262/6335adaa-0f8b-4dc0-a42f-c4fdb0beaf27)

![photo_2024-03-19_14-55-52](https://github.com/zxing/zxing/assets/66029262/14791de1-8cd1-4cea-96d2-a2a4fdbb7d01)

Can you help me?

**Comment by axxel** [comment]
Can you post the QRCode image itself that fails to decode?

**Comment by kkkaktusss** [comment]
i fixed that. Now, i push in zxing crop image and that worked. But anyway, why zxing recognize multiformat, if i push only qr_code type  ?

**Comment by axxel** [comment]
> i fixed that. Now, i push in zxing crop image and that worked. But anyway, why zxing recognize multiformat, if i push only qr_code type ?

Well, with the `reader.Options.PossibleFormats = new BarcodeFormat[] { BarcodeFormat.QR_CODE, BarcodeFormat.EAN_8, BarcodeFormat.UPC_E };` you explicitly look for EAN_8 as well. The reason you are getting a false positive EAN_8 is because of the quality of the EAN_8 detector. I assume the one used by ZXing.NET is still the same as the one implemented in the original Java ZXing library. I'm the maintainer of the [zxing-cpp](https://github.com/zxing-cpp/zxing-cpp) project and have reimplemented the EAN_8 detector/decoder (among others) which resulted in this specific case in a substantially reduced false positive rate. There is a .NET wrapper available as well: https://www.nuget.org/packages/ZXingCpp
